config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get '/search', to: 'articles#search'
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: :true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: :true, length: { minimum: 10, maximum: 2500 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 25 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }

  has_many :articles, dependent: :destroy
  validates :username, presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
            presence: true,
            length: { maximum: 100 },
            format: { with: VALID_EMAIL_REGEX }

  has_secure_password
  # At least 6 characters long and max 50
  PASSWORD_REQUIREMENTS = /\A
  (?=.{6,70})
  /x
  validates :password_digest, format: PASSWORD_REQUIREMENTS
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    # Memoization
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    # Return boolean
    !!current_user
  end

  def require_user
    return if logged_in?

    flash[:alert] = 'You must be logged in to perform that action'
    redirect_to login_path
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :require_user, except: %i[show index]
  before_action :require_same_user, only: %i[edit update destroy]

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = 'The article has been created'
      redirect_to @article
    else
      render 'new'
    end
  end

  def show; end

  def index
    @articles = Article.reorder("created_at ASC").paginate(page: params[:page], per_page: 5)

  end

  def search
    if params[:search].blank?
      redirect_to articles_path
    else
      @parameter = params[:search].downcase
      @articles = Article.all.where("lower(title) LIKE :search OR lower(description) LIKE :search", search: "%#{@parameter}%")
    end
  end

  def edit; end

  def update
    if @article.update(article_params)
      flash[:notice] = 'Article has been updated'
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  # Whitelist params
  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = 'You can only edit or delete your own article'
      redirect_to @article
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(cat_params)
    if @category.save
      flash[:notice] = 'Category has been added'
      redirect_to @category
    else
      render 'new'
    end
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(cat_params)
      flash[:notice] = 'Updated category name'
      redirect_to @category
    else
      render 'edit'
    end
  end

  private

  def cat_params
    params.require(:category).permit(:name)
  end

  def require_admin
    unless logged_in? && current_user.admin?
      flash[:alert] = 'You are not the administrator to perform that action'
      redirect_to categories_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    redirect_to articles_path if logged_in?
  end

  def about; end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = 'Logged in succesfully'
      redirect_to user
    else
      # flash.now because there's no redirect
      flash.now[:alert] = 'Incorrect email or password'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'You have successfully logged out'
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :require_user, only: %i[edit update]
  before_action :require_same_user, only: %i[edit update destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the new BloggedApp #{@user.username}!"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5) # Instead of adding obj in render
  end

  def index
    @users = User.reorder("created_at DESC").paginate(page: params[:page], per_page: 5)
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:notice] = 'Account succesfully updated'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = 'Account and all associated articles has been permanently deleted'
    redirect_to root_path
  end

  private

  # Whitelist params
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own profile"
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80 })
    email = user.email
    hash = Digest::MD5.hexdigest(email)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: 'rounded mx-auto d-block')
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center mb-5">
      <div class="col-8">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <% if article.categories.any? %>
              <%= render article.categories %>
            <% end %>
            <%= link_to gravatar_for(article.user, size: 40), user_path(article.user) %>
            <% if article.user %>
              <%= link_to article.user.username, user_path(article.user), class: "text-success" %>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to 'Show', article_path(article), class: "btn btn-info" %>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
              <%= link_to 'Edit', edit_article_path(article), class: "btn btn-warning" %>
              <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small><%= time_ago_in_words(article.created_at) %>,
              <%= time_ago_in_words(article.updated_at) %>
            </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">

  <div class="row justify-content-center text-white">
    <div class="col-10">
      <%= render 'shared/errors', obj: @article %>
    </div>
    <div class="col-10">
      <%= form_with(model: @article, class: "shadow p-4 mb-3 bg-limenew rounded", local: true) do |form| %>
        <div class="form-group row">
          <%= form.label :title, class: "col-2" %>
          <div class="col-10">
            <%= form.text_field :title, class: "form-control shadow rounded", placeholder: "Article title" %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :description, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= form.text_area :description, rows: 12, class: "form-control shadow rounded", placeholder: "Article description" %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :category, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= form.collection_select(:category_ids, Category.all, :id, :name, { prompt: 'Select categories
            (optional)' }, { multiple: true, class: "custom-select shadow rounded", size: "8" }) %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= form.submit class: "btn btn-light btn-lg" %>
        </div>
      <% end %>
      <div class="text-center justify-content-center mb-2">
        <%= link_to 'Return to articles', articles_path, class: "text-center btn btn-sm btn-secondary" %>
      </div>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h2 class="text-center mt-3">Articles:</h2>

<div class="d-flex justify-content-center mb-5">
  <%= will_paginate @articles %>
</div>

<%= render 'articles/article' %>

<div class="d-flex justify-content-center mb-3">
  <%= will_paginate @articles %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create new article</h1>

<%= render 'form' %>

app/views/articles/search.html.erb
<h1 class="text-center mt-3">Search results</h1>

<%= render 'articles/article' %>

app/views/articles/show.html.erb
<h3 class="text-center mt-4"><%= @article.title %></h3>

<div class="container">
  <div class="row justify-content-md-center mt-4">
    <div class="col-10">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          <% if @article.categories.any? %>
            <%= render @article.categories %>
          <% end %>
          <%= link_to gravatar_for(@article.user, size: 40), user_path(@article.user) %>
          <%= @article.user.username if @article.user %>
        </div>
        <div class="card-body">
          <div class="card-text text-left"><%= simple_format(@article.description) %></div>
          <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
            <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-warning" %>
            <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small><%= time_ago_in_words(@article.created_at) %>,
            <%= time_ago_in_words(@article.updated_at) %>
          </small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-success mb-2 mr-1" %>

app/views/categories/_form.html.erb
<div class="container">
  <div class="row justify-content-center text-white">
    <div class="col-10">
      <%= render 'shared/errors', obj: @category %>
    </div>
    <div class="col-6">
      <%= form_with(model: @category, class: "shadow p-4 mb-3 bg-limenew rounded", local: true) do |form| %>
        <div class="form-group row">
          <%= form.label :name, 'Category: ', class: "col-2" %>
          <div class="col-10">
            <%= form.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a category name" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= form.submit class: "btn btn-light" %>
        </div>
      <% end %>
      <div class="text-center justify-content-center mb-2">
        <%= link_to 'Return to categories', categories_path, class: "text-center btn btn-sm btn-secondary" %>
      </div>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4 mb-4">Edit a category</h1>

<%= render 'categories/form' %>

app/views/categories/index.html.erb
<h1 class="text-center mt-4 mb-4">Categories</h1>

<div class="d-flex justify-content-center mb-5">
  <%= will_paginate @categories %>
</div>

<div class="container">
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center mb-5">
      <div class="col-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
            <p class="card-text"><%= pluralize(category.articles.count, 'article') %></p>
          </div>
          <div class="card-footer text-muted">
            <small><%= time_ago_in_words(category.created_at) %>,
              <%= time_ago_in_words(category.updated_at) %>
            </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="d-flex justify-content-center mb-3">
  <%= will_paginate @categories %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4 mb-4">Create a new category</h1>

<%= render 'categories/form' %>

app/views/categories/show.html.erb
<h1 class="text-center mt-4 mb-4">Category: <%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
  <div class="text-center mt-4 mb-4">
    <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-outline-info" %>
  </div>
<% end %>

<div class="d-flex justify-content-center mb-5">
  <%= will_paginate @articles %>
</div>

<h3 class="text-center mx-3">Articles:</h3>
<%= render 'articles/article' %>

<div class="d-flex justify-content-center mb-3">
  <%= will_paginate @articles %>
</div>

app/views/layouts/_footer.html.erb
<footer class="py-4 bg-dark flex-shrink-0">
  <div class="container text-center text-white-50">
    New BloggedApp by
    <a href="https://github.com/bonikku" class="text-white">Marcin Kokoszka (Nikola B.) </a>
  </div>
  <div class="text-center"><%= link_to 'About', about_path, class: "text-dark badge badge-light" %></div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Blogged!', root_path, class: 'navbar-brand', id: 'logo' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <!--      <li class="nav-item active">-->
      <%#= link_to 'Articles', articles_path, class: 'nav-link' %>
      <!--      </li>-->
      <li class="nav-item">
        <%= link_to "Users", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? %>
            <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
          <% end %>
          <%= link_to "View articles", articles_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "View categories", categories_path, class: "dropdown-item" %>
          <% if logged_in? && current_user.admin? %>
            <%= link_to "Create categories", new_category_path, class: "dropdown-item" %>
          <% end %>
        </div>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
            <%= "(Admin)" if current_user.admin? %><%= current_user.username %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Edit profile", edit_user_path(current_user), class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Logout', logout_path, class: "dropdown-item", method: :delete %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Login', login_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <!--    <form class="form-inline my-2 my-lg-0">-->
    <!--      <input class="form-control mr-sm-2" type="search" placeholder="Search for an article" aria-label="Search">-->
    <!--      <button class="btn btn-light my-2 my-sm-0" type="submit">Search</button>-->
    <!--    </form>-->
    <%= form_tag(search_path, :method => 'get', class: 'form-inline my-2 my-lg-0') do %>
      <%= search_field_tag :search, params[:search], placeholder: 'Search for articles', class: 'form-control mr-sm-2' %>
      <%= button_tag 'Search', :class => 'btn btn-light my-2 my-sm-0', :name => nil %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>BloggedApp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= favicon_link_tag asset_path('favicon.png') %>
</head>

<body class="d-flex flex-column">
<%= render 'layouts/nav' %>
<%= render 'layouts/messages' %>
<div class="flex-grow-1 flex-shrink-0">
  <%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<div class="container mt-lg-5">
  <div class="card">
    <div class="card-header">
      <h1 class="text-center">About Bloggy</h1>
    </div>
    <div class="card-body">
      <p>BloggedApp is a second version of my very first Rails blog project, it's still quite simple but this version is
        polished and has few additional functions like searching</p>
      <p>I decided to rewrite it to polish rails basics. Later I want to add ActiveStorage to upload files and photos for
        articles but for now I'll focus on my next project which is 7Chat.
      </p>
      <p>Link to previous version on <%= link_to 'heroku', 'https://bloggy-nikola.herokuapp.com/' %></p>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container mt-5">
  <div class="jumbotron text-center" id=home-container>
    <h1 class="display-4">New Blogging App</h1>
    <p class="lead">Welcome to new BloggedApp!</p>
    <hr class="my-4">
    <p>Sign up and create your own article!</p>
    <%= link_to 'Sign up!', signup_path, class: "btn btn-light btn-lg" %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading text-center">Something went wrong with saving the <%= obj.class.name.downcase %></h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container mt-4">

  <div class="row justify-content-center text-white">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
    </div>
    <div class="col col-md-5">
      <%= form_with(model: @user, class: "shadow p-4 mb-3 bg-limenew rounded", local: true) do |form| %>
        <div class="form-group font-weight-bold">
          <%= form.label :username, class: "col-2" %>
          <div class="m-1">
            <%= form.text_field :username, class: "form-control shadow rounded", placeholder: "Enter your username" %>
          </div>
        </div>

        <div class="form-group font-weight-bold">
          <%= form.label :email, class: "col-2 col-form-label" %>
          <div class="m-1">
            <%= form.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email" %>
          </div>
        </div>

        <div class="form-group font-weight-bold">
          <%= form.label :password, class: "col-2 col-form-label" %>
          <div class="m-1">
            <%= form.password_field :password, class: "form-control shadow rounded", placeholder: "Enter password" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= form.submit(@user.new_record? ? "Sign up" : "Edit account", class: "btn btn-primary btn-lg") %>
        </div>
        <% if logged_in? %>
          <div class="form-group row justify-content-center">
            <%= link_to 'Delete account', user_path(current_user), class: "btn btn-danger btn-sm", method: :delete, data: { confirm: 'Are you sure you want to delete your account?' } %>
          </div>
        <% end %>
      <% end %>
      <div class="text-center justify-content-center mb-2">
        <%= link_to 'Return to articles', articles_path, class: "text-center btn btn-sm btn-secondary" %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit profile</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Users</h1>

<div class="d-flex justify-content-center mb-5">
  <%= will_paginate @users %>
</div>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center mt-5">
      <div class="col-8">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <% #user_path(user) %>
            <%= link_to user.username, user %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to gravatar_for(user, size: 140), user %></h5>
            <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
            <%= link_to 'View profile', user, class: "btn btn-info" %>
            <% if logged_in? %>
              <% if user == current_user || current_user.admin? %>
                <%= link_to 'Edit profile', edit_user_path(user), class: "btn btn-warning" %>
              <% end %>
              <% if current_user.admin? %>
                <%= link_to 'Delete', user_path(user), class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure you want to delete this user?" } %>
              <% end %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small><%= time_ago_in_words(user.created_at) %>,
              <%= time_ago_in_words(user.updated_at) %>
            </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="d-flex justify-content-center mb-3">
  <%= will_paginate @users %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %></h1>


<%= gravatar_for @user, size: 160 %>

<% if logged_in? && @user == current_user %>
  <div class="text-center mt-4 mb-4">
    <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
  </div>
<% end %>

<div class="d-flex justify-content-center mb-5">
  <%= will_paginate @articles %>
</div>

<h3 class="text-center mx-3">Articles:</h3>
<%= render 'articles/article' %>

<div class="d-flex justify-content-center mb-3">
  <%= will_paginate @articles %>
</div>